/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.94
 * Generated at: 2019-11-20 13:41:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/common/top.jsp", Long.valueOf(1573358130577L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh_CN\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery/pagination/pagination.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".tree li {\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table tbody tr:nth-child(odd) {\r\n");
      out.write("\tbackground: #F4F4F4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table tbody td:nth-child(even) {\r\n");
      out.write("\tcolor: #C00;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" style=\"font-size: 32px;\" href=\"#\">众筹平台\r\n");
      out.write("\t\t\t\t\t\t- 用户维护</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t ");
      out.write("\r\n");
      out.write("<li style=\"padding-top: 8px;\">\r\n");
      out.write("\t<div class=\"btn-group\">\r\n");
      out.write("\t\t<button type=\"button\"\r\n");
      out.write("\t\t\tclass=\"btn btn-default btn-success dropdown-toggle\"\r\n");
      out.write("\t\t\tdata-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t<i class=\"glyphicon glyphicon-user\"></i>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("<span\r\n");
      out.write("\t\t\t\tclass=\"caret\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"glyphicon glyphicon-cog\"></i> 个人设置</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"glyphicon glyphicon-comment\"></i>\r\n");
      out.write("\t\t\t\t\t消息</a></li>\r\n");
      out.write("\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/logout.do\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-off\"></i> 退出系统</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</li>\r\n");
      out.write("<li style=\"margin-left: 10px; padding-top: 8px;\">\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-default btn-danger\">\r\n");
      out.write("\t\t<span class=\"glyphicon glyphicon-question-sign\"></span> 帮助\r\n");
      out.write("\t</button>\r\n");
      out.write("</li>");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<form class=\"navbar-form navbar-right\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Search...\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-3 col-md-2 sidebar\">\r\n");
      out.write("\t\t\t\t<div class=\"tree\">\r\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/common/menu.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"panel-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-th\"></i> 数据列表\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<form class=\"form-inline\" role=\"form\" style=\"float: left;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group has-feedback\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group-addon\">查询条件</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"queryText\" class=\"form-control has-success\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"请输入查询条件\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<button id=\"queryBtn\" type=\"button\" class=\"btn btn-warning\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-search\"></i> 查询\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-danger\" id=\"deleteBatchBtn\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"float: right; margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\" glyphicon glyphicon-remove\"></i> 删除\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" \r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"float: right;\" onclick=\"window.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/add.htm'\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-plus\"></i> 新增\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<hr style=\"clear: both;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"table  table-bordered\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th width=\"30\">#</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th width=\"30\"><input id=\"allCheckbox\" type=\"checkbox\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>账号</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>名称</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>邮箱地址</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th width=\"100\">操作</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"6\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul id=\"Pagination\" class=\"pagination\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tfoot>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/script/docs.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery/layer/layer.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery/pagination/jquery.pagination.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("            $(function () {\r\n");
      out.write("\t\t\t    $(\".list-group-item\").click(function(){\r\n");
      out.write("\t\t\t\t    if ( $ (this).find(\"ul\") ) {\r\n");
      out.write("\t\t\t\t\t\t$(this).toggleClass(\"tree-closed\");\r\n");
      out.write("\t\t\t\t\t\tif ( $(this).hasClass(\"tree-closed\") ) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"ul\", this).hide(\"fast\");\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"ul\", this).show(\"fast\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    queryPageUser(0);\r\n");
      out.write("\t\t\t    showMenu();\r\n");
      out.write("            });\r\n");
      out.write("            $(\"tbody .btn-success\").click(function(){\r\n");
      out.write("                window.location.href = \"assignRole.html\";\r\n");
      out.write("            });\r\n");
      out.write("            $(\"tbody .btn-primary\").click(function(){\r\n");
      out.write("                window.location.href = \"edit.html\";\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            function pageChange( pageno ) {\r\n");
      out.write("//            \twindow.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/index.do?pageno=\"+pageno;\r\n");
      out.write("\t\t\t\tqueryPageUser(pageno);\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            var jsonObj = {\r\n");
      out.write("        \t\t\t\"pageno\" : 1,\r\n");
      out.write("        \t\t\t\"pagesize\" : 10 \r\n");
      out.write("        \t\t};\r\n");
      out.write("            \r\n");
      out.write("            var loadingIndex = -1 ;\r\n");
      out.write("            function queryPageUser(pageIndex){     //参数默认pageIndex\r\n");
      out.write("            \tjsonObj.pageno = pageIndex + 1;\r\n");
      out.write("            \t$.ajax({\r\n");
      out.write("            \t\ttype : \"POST\",\r\n");
      out.write("            \t\tdata : jsonObj,\r\n");
      out.write("            \t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/doIndex.do\",\r\n");
      out.write("            \t\tbeforeSend : function(){\r\n");
      out.write("            \t\t\tloadingIndex = layer.load(2, {time: 10*1000});\r\n");
      out.write("            \t\t\treturn true ;\r\n");
      out.write("            \t\t},\r\n");
      out.write("            \t\tsuccess : function(result){\r\n");
      out.write("            \t\t\tlayer.close(loadingIndex);\r\n");
      out.write("            \t\t\tif(result.success){\r\n");
      out.write("            \t\t\t\tvar page = result.page ;\r\n");
      out.write("            \t\t\t\tvar data = page.data ;\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\tvar content = '';\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\t$.each(data,function(i,n){ \r\n");
      out.write("            \t\t\t\t\tcontent+='<tr>';\r\n");
      out.write("                \t\t\t\tcontent+='  <td>'+(i+1)+'</td>';\r\n");
      out.write("                \t\t\t\tcontent+='  <td><input id=\"'+n.id+'\" loginacct=\"'+n.loginacct+'\" type=\"checkbox\"></td>';\r\n");
      out.write("                \t\t\t\tcontent+='  <td>'+n.loginacct+'</td>';\r\n");
      out.write("                \t\t\t\tcontent+='  <td>'+n.username+'</td>';\r\n");
      out.write("                \t\t\t\tcontent+='  <td>'+n.email+'</td>';\r\n");
      out.write("                \t\t\t\tcontent+='  <td>';\r\n");
      out.write("                \t\t\t\tcontent+='\t  <button type=\"button\" onclick=\"window.location.href=\\'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/assignRole.htm?id='+n.id+'\\'\" class=\"btn btn-success btn-xs\"><i class=\" glyphicon glyphicon-check\"></i></button>';\r\n");
      out.write("                \t\t\t\tcontent+='\t  <button type=\"button\" onclick=\"window.location.href=\\'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/toUpdate.htm?id='+n.id+'\\'\" class=\"btn btn-primary btn-xs\"><i class=\" glyphicon glyphicon-pencil\"></i></button>';\r\n");
      out.write("                \t\t\t\tcontent+='\t  <button type=\"button\" onclick=\"deleteUser('+n.id+',\\''+n.loginacct+'\\')\" class=\"btn btn-danger btn-xs\"><i class=\" glyphicon glyphicon-remove\"></i></button>';\r\n");
      out.write("                \t\t\t\tcontent+='  </td>';\r\n");
      out.write("                \t\t\t\tcontent+='</tr>';\r\n");
      out.write("            \t\t\t\t});\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\t$(\"tbody\").html(content);\r\n");
      out.write("            \t\t\t\t// 创建分页\r\n");
      out.write("            \t\t\t\t$(\"#Pagination\").pagination(page.totalsize, {    //page.totalsize查询出的总条数\r\n");
      out.write("            \t\t\t\t\tnum_edge_entries: 2, //边缘页数                             \r\n");
      out.write("            \t\t\t\t\tnum_display_entries: 3, //主体页数\t\t\t\r\n");
      out.write("            \t\t\t\t\tcallback: queryPageUser,\t\t\t\t\t//回调函数\r\n");
      out.write("            \t\t\t\t\titems_per_page: 10, //每页显示页数                       //与自己设置的pagesize相同\r\n");
      out.write("            \t\t\t\t\tcurrent_page:(page.pageno-1),               //当前页，0代表第一页\r\n");
      out.write("            \t\t\t\t\tprev_text : \"上一页\",                       //前一页”分页按钮上显示的文字\r\n");
      out.write("            \t\t\t\t\tnext_text : \"下一页\"\t\t\t\t\t\t\t//“下一页”分页按钮上显示的文字\r\n");
      out.write("            \t\t\t\t});\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t}else{\r\n");
      out.write("            \t\t\t\tlayer.msg(result.message, {time:1000, icon:5, shift:6});\r\n");
      out.write("            \t\t\t}\r\n");
      out.write("            \t\t},\r\n");
      out.write("            \t\terror : function(){\r\n");
      out.write("            \t\t\tlayer.msg(\"加载数据失败!\", {time:1000, icon:5, shift:6});\r\n");
      out.write("            \t\t}\r\n");
      out.write("            \t});\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            function deleteUser(id,loginacct){\r\n");
      out.write("            \tlayer.confirm(\"确认要删除[\"+loginacct+\"]用户吗?\",  {icon: 3, title:'提示'}, function(cindex){\r\n");
      out.write("            \t\tlayer.close(cindex);\r\n");
      out.write("            \t\t$.ajax({\r\n");
      out.write("                \t\ttype : \"POST\",\r\n");
      out.write("                \t\tdata : {\r\n");
      out.write("                \t\t\t\"id\" : id\r\n");
      out.write("                \t\t},\r\n");
      out.write("                \t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/doDelete.do\",\r\n");
      out.write("                \t\tbeforeSend : function() {   \r\n");
      out.write("                \t\t\treturn true ;\r\n");
      out.write("                \t\t},\r\n");
      out.write("                \t\tsuccess : function(result){\r\n");
      out.write("                \t\t\tif(result.success){\r\n");
      out.write("                \t\t\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/index.htm\";\r\n");
      out.write("                \t\t\t}else{\r\n");
      out.write("                \t\t\t\tlayer.msg(\"删除用户失败\", {time:1000, icon:5, shift:6}); \r\n");
      out.write("                \t\t\t}\r\n");
      out.write("                \t\t},\r\n");
      out.write("                \t\terror : function(){\r\n");
      out.write("                \t\t\tlayer.msg(\"删除失败\", {time:1000, icon:5, shift:6}); \r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t});\r\n");
      out.write("    \t\t\t}, function(cindex){\r\n");
      out.write("    \t\t\t    layer.close(cindex);\r\n");
      out.write("    \t\t\t});            \t         \r\n");
      out.write("            \t\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            $(\"#queryBtn\").click(function(){\r\n");
      out.write("            \tvar queryText = $(\"#queryText\").val();\r\n");
      out.write("            \tjsonObj.queryText =  queryText ;\r\n");
      out.write("            \tqueryPageUser(0);\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            $(\"#allCheckbox\").click(function(){\r\n");
      out.write("            \tvar checkStatus  = this.checked;\r\n");
      out.write("            \t/* alert(checkStatus); */\r\n");
      out.write("            \t$(\"tbody tr td input[type='checkbox']\").prop(\"checked\",checkStatus);\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            $(\"#deleteBatchBtn\").click(function(){\r\n");
      out.write("            \tvar selectCheckbox = $(\"tbody tr td input:checked\");\r\n");
      out.write("            \tif(selectCheckbox.length==0){\r\n");
      out.write("            \t\tlayer.msg(\"请至少选择一个用户删除\", {time:1000, icon:5, shift:6});\r\n");
      out.write("            \t\treturn false;\r\n");
      out.write("            \t}\r\n");
      out.write("            \t\r\n");
      out.write("            \tvar jsonObj = {};\r\n");
      out.write("            \t\r\n");
      out.write("            \t$.each(selectCheckbox,function(i,n){\r\n");
      out.write("            \t\tjsonObj[\"datas[\"+i+\"].id\"] = n.id;\r\n");
      out.write("            \t\tjsonObj[\"datas[\"+i+\"].loginacct\"] = n.loginacct;\r\n");
      out.write("            \t})\r\n");
      out.write("            \tlayer.confirm(\"确认要删除所选用户吗?\",  {icon: 3, title:'提示'}, function(cindex){\r\n");
      out.write("            \t\tlayer.close(cindex);\r\n");
      out.write("            \t\t$.ajax({\r\n");
      out.write("                \t\ttype : \"POST\",\r\n");
      out.write("                \t\tdata : jsonObj,\r\n");
      out.write("                \t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/doDeleteBatch.do\",\r\n");
      out.write("                \t\tbeforeSend : function() {   \r\n");
      out.write("                \t\t\treturn true ;\r\n");
      out.write("                \t\t},\r\n");
      out.write("                \t\tsuccess : function(result){\r\n");
      out.write("                \t\t\tif(result.success){\r\n");
      out.write("                \t\t\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/index.htm\";\r\n");
      out.write("                \t\t\t}else{\r\n");
      out.write("                \t\t\t\tlayer.msg(\"删除用户失败\", {time:1000, icon:5, shift:6}); \r\n");
      out.write("                \t\t\t}\r\n");
      out.write("                \t\t},\r\n");
      out.write("                \t\terror : function(){\r\n");
      out.write("                \t\t\tlayer.msg(\"删除失败\", {time:1000, icon:5, shift:6}); \r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t});\r\n");
      out.write("    \t\t\t}, function(cindex){\r\n");
      out.write("    \t\t\t    layer.close(cindex);\r\n");
      out.write("    \t\t\t});            \t         \r\n");
      out.write("            \t          \t\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/script/menu.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
