/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.94
 * Generated at: 2019-11-11 08:28:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.role;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/jsp/common/top.jsp", Long.valueOf(1573358130577L));
    _jspx_dependants.put("/WEB-INF/jsp/common/menu.jsp", Long.valueOf(1573279674257L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/main.css\">\r\n");
      out.write("<style>\r\n");
      out.write(".tree li {\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table tbody tr:nth-child(odd) {\r\n");
      out.write("\tbackground: #F4F4F4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table tbody td:nth-child(even) {\r\n");
      out.write("\tcolor: #C00;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" style=\"font-size: 32px;\" href=\"#\">众筹平台\r\n");
      out.write("\t\t\t\t\t\t- 角色维护</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t<li style=\"padding-top: 8px;\">\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("<li style=\"padding-top: 8px;\">\r\n");
      out.write("\t<div class=\"btn-group\">\r\n");
      out.write("\t\t<button type=\"button\"\r\n");
      out.write("\t\t\tclass=\"btn btn-default btn-success dropdown-toggle\"\r\n");
      out.write("\t\t\tdata-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t<i class=\"glyphicon glyphicon-user\"></i>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("<span\r\n");
      out.write("\t\t\t\tclass=\"caret\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"glyphicon glyphicon-cog\"></i> 个人设置</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"glyphicon glyphicon-comment\"></i>\r\n");
      out.write("\t\t\t\t\t消息</a></li>\r\n");
      out.write("\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/logout.do\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-off\"></i> 退出系统</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</li>\r\n");
      out.write("<li style=\"margin-left: 10px; padding-top: 8px;\">\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-default btn-danger\">\r\n");
      out.write("\t\t<span class=\"glyphicon glyphicon-question-sign\"></span> 帮助\r\n");
      out.write("\t</button>\r\n");
      out.write("</li>");
      out.write("\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<form class=\"navbar-form navbar-right\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Search...\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-3 col-md-2 sidebar\">\r\n");
      out.write("\t\t\t\t<div class=\"tree\">\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<ul style=\"padding-left:0px;\" class=\"list-group\">\r\n");
      out.write("\r\n");
      out.write("\t<li class=\"list-group-item tree-closed\" >\r\n");
      out.write("\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/main.htm\"><i class=\"glyphicon glyphicon-dashboard\"></i> 控制面板</a> \r\n");
      out.write("\t</li>\r\n");
      out.write("\r\n");
      out.write("\t<li class=\"list-group-item tree-closed\">\r\n");
      out.write("\t\t<span><i class=\"glyphicon glyphicon glyphicon-tasks\"></i> 权限管理 <span class=\"badge\" style=\"float:right\">3</span></span> \r\n");
      out.write("\t\t<ul style=\"margin-top:10px;display:none;\">\r\n");
      out.write("\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/index.htm\"><i class=\"glyphicon glyphicon-user\"></i> 用户维护</a> \r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/role/index.htm\"><i class=\"glyphicon glyphicon-king\"></i> 角色维护</a> \r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/permission/index.htm\"><i class=\"glyphicon glyphicon-lock\"></i> 许可维护</a> \r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"list-group-item tree-closed\">\r\n");
      out.write("\t\t<span><i class=\"glyphicon glyphicon-ok\"></i> 业务审核 <span class=\"badge\" style=\"float:right\">3</span></span> \r\n");
      out.write("\t\t<ul style=\"margin-top:10px;display:none;\">\r\n");
      out.write("\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t<a href=\"auth_cert.html\"><i class=\"glyphicon glyphicon-check\"></i> 实名认证审核</a> \r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t<a href=\"auth_adv.html\"><i class=\"glyphicon glyphicon-check\"></i> 广告审核</a> \r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t<a href=\"auth_project.html\"><i class=\"glyphicon glyphicon-check\"></i> 项目审核</a> \r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"list-group-item tree-closed\">\r\n");
      out.write("\t\t<span><i class=\"glyphicon glyphicon-th-large\"></i> 业务管理 <span class=\"badge\" style=\"float:right\">7</span></span> \r\n");
      out.write("\t\t<ul style=\"margin-top:10px;display:none;\">\r\n");
      out.write("\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/cert/index.htm\"><i class=\"glyphicon glyphicon-picture\"></i> 资质维护</a> \r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/type/index.htm\"><i class=\"glyphicon glyphicon-equalizer\"></i> 分类管理</a> \r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t<a href=\"process.html\"><i class=\"glyphicon glyphicon-random\"></i> 流程管理</a> \r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/advert/index.htm\"><i class=\"glyphicon glyphicon-hdd\"></i> 广告管理</a> \r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t<a href=\"message.html\"><i class=\"glyphicon glyphicon-comment\"></i> 消息模板</a> \r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/projectType/index.htm\"><i class=\"glyphicon glyphicon-list\"></i> 项目分类</a> \r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t<a href=\"tag.html\"><i class=\"glyphicon glyphicon-tags\"></i> 项目标签</a> \r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"list-group-item tree-closed\" >\r\n");
      out.write("\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/param/index.htm\"><i class=\"glyphicon glyphicon-list-alt\"></i> 参数管理</a> \r\n");
      out.write("\t</li>\r\n");
      out.write("\t\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"panel-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-th\"></i> 数据列表\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<form class=\"form-inline\" name=\"form\" style=\"float: left;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group has-feedback\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group-addon\">查询条件</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"queryText\" class=\"form-control has-success\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"请输入查询条件\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-warning\" onclick=\"queryRole()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-search\"></i> 查询\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"batchDelete\" type=\"button\" class=\"btn btn-danger\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"float: right; margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-remove\"></i> 删除\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"float: right;\" onclick=\"window.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/role/add.htm'\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-plus\"></i> 新增\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<hr style=\"clear: both;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"table  table-bordered\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th width=\"30\">#</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th width=\"30\"><input type=\"checkbox\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th width=\"100\">操作</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"6\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/script/docs.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery/layer/layer.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("            $(function () {\r\n");
      out.write("\t\t\t    $(\".list-group-item\").click(function(){\r\n");
      out.write("\t\t\t\t    if ( $(this).find(\"ul\") ) {\r\n");
      out.write("\t\t\t\t\t\t$(this).toggleClass(\"tree-closed\");\r\n");
      out.write("\t\t\t\t\t\tif ( $(this).hasClass(\"tree-closed\") ) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"ul\", this).hide(\"fast\");\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"ul\", this).show(\"fast\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\r\n");
      out.write("\t\t\t    queryPage(1);\r\n");
      out.write("\r\n");
      out.write("\t\t\t    showMenu();\r\n");
      out.write("\t\t\t   \r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            function changePageno( pageno ) {\r\n");
      out.write("            \t//window.location.href = \"");
      out.print(request.getContextPath() );
      out.write("/role/index.htm?pageno=\"+pageno;\r\n");
      out.write("            \tqueryPage(pageno);\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            //使用Ajax异步查询数据\r\n");
      out.write("            function queryPage( pageno ){\r\n");
      out.write("            \t\r\n");
      out.write("            \tvar dataObj = {\r\n");
      out.write("        \t\t\t\"pageno\" : pageno ,   //pageno 是属性名称,是否增加双引号无所谓\r\n");
      out.write("        \t\t\t\"pagesize\" : 9\r\n");
      out.write("        \t\t};\r\n");
      out.write("            \tif(condition){\r\n");
      out.write("            \t\tdataObj.queryText = $(\"#queryText\").val(); //增加模糊查询条件\r\n");
      out.write("            \t}\r\n");
      out.write("            \t\r\n");
      out.write("            \tvar loadingIndex = -1 ;\r\n");
      out.write("            \t$.ajax({\r\n");
      out.write("            \t\t\r\n");
      out.write("            \t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/role/pageQuery.do\",\r\n");
      out.write("            \t\ttype : \"post\",\r\n");
      out.write("            \t\tdata : dataObj,\r\n");
      out.write("            \t\tbeforeSend : function(){\r\n");
      out.write("            \t\t\tloadingIndex = layer.msg('数据查询中', {icon: 6});\r\n");
      out.write("            \t\t\treturn true ;\r\n");
      out.write("            \t\t},\r\n");
      out.write("            \t\tsuccess : function(result){\r\n");
      out.write("            \t\t\t//显示结果\r\n");
      out.write("            \t\t\tlayer.close(loadingIndex);\r\n");
      out.write("            \t\t\tif(result.success){\r\n");
      out.write("            \t\t\t\t//循环遍历,显示数据\r\n");
      out.write("            \t\t\t\tvar pageObj = result.page;\r\n");
      out.write("            \t\t\t\tvar roleList = pageObj.data ;\r\n");
      out.write("            \t\t\t\tvar content = \"\";\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\t$.each(roleList,function(i,n){\r\n");
      out.write("            \t\t\t\t\t\r\n");
      out.write("            \t\t\t\t\tcontent+=\"<tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t<td>\"+(i+1)+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t<td><input type='checkbox' value='\"+n.id+\"'></td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t<td>\"+n.name+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t<td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t\t<button type='button' onclick='window.location.href=\\\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/role/permission.htm?roleid=\"+n.id+\"\\\"' class='btn btn-success btn-xs'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t\t\t<i class=' glyphicon glyphicon-check'></i>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t\t</button>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t\t<button type='button' onclick='window.location.href=\\\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/role/edit.htm?pageno=\"+pageObj.pageno+\"&id=\"+n.id+\"\\\"' class='btn btn-primary btn-xs'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t\t\t<i class=' glyphicon glyphicon-pencil'></i>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t\t</button>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t\t<button type='button' class='btn btn-danger btn-xs' onclick='deleteRole(\"+n.id+\",\\\"\"+n.name+\"\\\")'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t\t\t<i class=' glyphicon glyphicon-remove'></i>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t\t</button>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"</tr>\";\r\n");
      out.write("            \t\t\t\t\t//$(\"tbody\").append(content);\r\n");
      out.write("            \t\t\t\t\t$(\"tbody\").html(content);\r\n");
      out.write("            \t\t\t\t});\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\t//拼接导航条\r\n");
      out.write("            \t\t\t\tvar pageContent = \"\";\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\tif(pageObj.pageno!=1){\r\n");
      out.write("            \t\t\t\t\tpageContent += '<li><a href=\"#\" onclick=\"changePageno('+(pageObj.pageno-1)+')\">上一页</a></li>';\r\n");
      out.write("            \t\t\t\t}\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\tfor(var i=1 ; i<=pageObj.totalno ; i++){\r\n");
      out.write("            \t\t\t\t\tif(i==pageObj.pageno){\r\n");
      out.write("\t            \t\t\t\t\tpageContent += '<li class=\"active\"><a href=\"#\" onclick=\"changePageno('+i+')\">'+i+'</a></li>';\r\n");
      out.write("            \t\t\t\t\t\t\r\n");
      out.write("            \t\t\t\t\t}else{\r\n");
      out.write("\t            \t\t\t\t\tpageContent += '<li><a href=\"#\" onclick=\"changePageno('+i+')\">'+i+'</a></li>';\r\n");
      out.write("            \t\t\t\t\t\t\r\n");
      out.write("            \t\t\t\t\t}\r\n");
      out.write("            \t\t\t\t}\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\tif(pageObj.pageno!=pageObj.totalno){\r\n");
      out.write("            \t\t\t\t\tpageContent += '<li><a href=\"#\" onclick=\"changePageno('+(pageObj.pageno+1)+')\">下一页</a></li>';\r\n");
      out.write("            \t\t\t\t}\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\t$(\".pagination\").html(pageContent);\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t}else{\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\tlayer.msg(\"角色分页查询数据失败\", {time:1000, icon:5, shift:6});\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t}\r\n");
      out.write("            \t\t},\r\n");
      out.write("            \t\terror : function(){\r\n");
      out.write("            \t\t\tlayer.msg(\"角色分页查询数据错误\", {time:1000, icon:5, shift:6});\r\n");
      out.write("            \t\t}\r\n");
      out.write("            \t\t\r\n");
      out.write("            \t});\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            var condition = false ;\r\n");
      out.write("            //条件查询\r\n");
      out.write("            function queryRole(){\r\n");
      out.write("            \tvar queryText = $(\"#queryText\");\r\n");
      out.write("            \t\r\n");
      out.write("            \tif(queryText.val()==\"\"){\r\n");
      out.write("            \t\tlayer.msg(\"查询条件不能为空\", {time:1000, icon:5, shift:6}, function(){\r\n");
      out.write("            \t\t\tqueryText.focus();\r\n");
      out.write("            \t\t});\r\n");
      out.write("            \t\treturn ;\r\n");
      out.write("            \t}\r\n");
      out.write("            \tcondition = true ;\r\n");
      out.write("            \tqueryPage(1);\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            function deleteRole(uid,name){\r\n");
      out.write("            \t\r\n");
      out.write("    \t\t\tlayer.confirm(\"是否要删除角色?\",  {icon: 3, title:'提示'}, function(cindex){\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t$.ajax({\r\n");
      out.write("    \t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/role/delete.do\",\r\n");
      out.write("    \t\t\t\t\ttype : \"POST\",\r\n");
      out.write("    \t\t\t\t\tdata : {uid:uid},\r\n");
      out.write("    \t\t\t\t\tsuccess : function(result){\r\n");
      out.write("    \t\t\t\t\t\tif(result.success){\r\n");
      out.write("    \t\t\t\t\t\t\tlayer.msg(\"删除\"+name+\"角色成功!\", {time:1000, icon:6}, function(){\r\n");
      out.write("    \t\t\t\t\t\t\t\tqueryPage(1);\r\n");
      out.write("    \t\t\t\t\t\t\t});\r\n");
      out.write("    \t\t\t\t\t\t}else{\r\n");
      out.write("    \t\t\t\t\t\t\tlayer.msg(\"删除\"+name+\"角色失败!\", {time:1000, icon:5, shift:6});\r\n");
      out.write("    \t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t});\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t    layer.close(cindex);\r\n");
      out.write("    \t\t\t}, function(cindex){    \t\t\t\t\r\n");
      out.write("    \t\t\t    layer.close(cindex);\r\n");
      out.write("    \t\t\t});\r\n");
      out.write("            \t\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            $(\".table thead :checkbox\").click(function(){\r\n");
      out.write("            \tvar checked = this.checked ;\r\n");
      out.write("            \tvar checkboxList = $(\".table tbody :checkbox\");\r\n");
      out.write("            \t$.each(checkboxList,function(i,n){\r\n");
      out.write("            \t\tn.checked = checked ;\r\n");
      out.write("            \t});\r\n");
      out.write("            });\r\n");
      out.write("\t\t\t//传递多个对象的方式\r\n");
      out.write("            $(\"#batchDelete\").click(function(){\r\n");
      out.write("            \tvar checkedList = $(\"table tbody input:checked\");\r\n");
      out.write("            \tif(checkedList.length>0){\r\n");
      out.write("            \t\tlayer.confirm(\"确定要删除吗?\",  {icon: 3, title:'提示'}, function(cindex){\r\n");
      out.write("            \t\t\t\r\n");
      out.write("            \t\t\tvar datas = {};\r\n");
      out.write("            \t\t\t\r\n");
      out.write("            \t\t\t$.each(checkedList,function(i,n){\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\tdatas[\"datas[\"+i+\"].id\"]=n.value;\r\n");
      out.write("            \t\t\t\tdatas[\"datas[\"+i+\"].name\"]=\"111\";\r\n");
      out.write("            \t\t\t});\r\n");
      out.write("            \t\t\t\r\n");
      out.write("            \t\t\t$.ajax({\r\n");
      out.write("            \t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/role/batchDelete.do\",\r\n");
      out.write("            \t\t\t\ttype : \"POST\",\r\n");
      out.write("            \t\t\t\tdata : datas ,\r\n");
      out.write("            \t\t\t\tsuccess : function(result){\r\n");
      out.write("            \t\t\t\t\tif(result.success){\r\n");
      out.write("\t            \t\t\t\t\tlayer.msg(\"删除角色成功!\", {time:1000, icon:6}, function(){\r\n");
      out.write("\t    \t\t\t\t\t\t\t\tqueryPage(1);\r\n");
      out.write("\t    \t\t\t\t\t\t\t});\r\n");
      out.write("            \t\t\t\t\t}else{\r\n");
      out.write("            \t\t\t\t\t\tlayer.msg(\"删除角色失败!\", {time:1000, icon:5});\r\n");
      out.write("            \t\t\t\t\t}\r\n");
      out.write("            \t\t\t\t}\r\n");
      out.write("            \t\t\t});\r\n");
      out.write("        \t\t\t    layer.close(cindex);\r\n");
      out.write("        \t\t\t}, function(cindex){\r\n");
      out.write("        \t\t\t    layer.close(cindex);\r\n");
      out.write("        \t\t\t});\r\n");
      out.write("            \t}\r\n");
      out.write("            });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/script/menu.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
